Corrigindo Erro de Quando Existem Nomeações e Exonerações Num Mesmo Ato
danielfireman/ifal-qd pull request #106
Opened 2023-02-06 23:51 UTC by alex-custodio

2023-02-07 00:00 UTC, alex-custodio commented
OBS: as variáveis `texto_nomeacoes` e `texto_exoneracoes` são lista para caso existam mais de uma nomeação e exoneração no ato seja possível capturar. Mesmo que a gente não tenha econtrado um ato assim, já previne de surpresas no futuro.

2023-02-07 18:18 UTC, danielfireman requested changes

2023-02-07 18:18 UTC, danielfireman commented on post_proc.py
> +        if self.possui_nomeacoes:
Por favor inverter a ordem. Primeiro checar ambos ao mesmo tempo (e já retornar), caso contrário, checar cada um. Creio que dá para deixar mais organizado o método como um todo.

2023-02-07 18:18 UTC, danielfireman commented on post_proc.py
> +        if self.possui_nomeacoes and self.possui_exoneracoes:
Colocar um comentário resumindo a lógica usada para separar os textos.

2023-02-09 13:23 UTC, danielfireman approved these changes

2023-02-09 13:23 UTC, merged