Criar JSON sobre os diários
danielfireman/ifal-qd pull request #133
Opened 2023-03-29 21:02 UTC by alex-custodio

Esta PR possui:
- Script em python que gera arquivos json a partir dos arquivos de resumo-extracao.json.
- Arquivo JSON gerado através do código com as informações dos diários de 2023 (docs/site/diarios/2023.json)

2023-03-29 21:47 UTC, danielfireman requested changes

2023-03-29 21:47 UTC, danielfireman commented on docs/site/criar_json_diarios.py
> +contagem_mensal = defaultdict(lambda: defaultdict(int))
Só por curiosidade, pq você está usando `defaultdict`?

2023-03-29 21:47 UTC, danielfireman commented on docs/site/criar_json_diarios.py
> +        for diario in diarios:
Reflexão: da forma que você organizou os dados, para renderizar a página inicial, você vai precisar carregar todos os dados de todos os anos de todos os municípios. Isso é bem pesado.

Minha sugestão é que você mude a forma de organizar as informações. Gere um arquivo por município contendo  uma lista com as informações por ano. Exemplo:

`arapiraca_inicial.json`

```json
{
  "id": "arapiraca",
  "resumo": {
       "qtd_diarios": 222,
   },
   "detalhe": [
   { 
       "ano": "2014":
        "qtd_diarios": 111,
   },
   { 
       "ano": "2015":
        "qtd_diarios": 111,
   }
  ]
}
```

Note que, para renderizar a página inicial (lembrando que a gente removeu a opção de mostrar todos os municípios), agora você só precisa carregar um arquivo com os dados de um único município.

2023-03-29 21:59 UTC, alex-custodio commented on docs/site/criar_json_diarios.py
> +contagem_mensal = defaultdict(lambda: defaultdict(int))
Eu usei ele por que ele ajuda a incrementar a quantidade de diários de maneira mais ágil, sem ele eu teria que adicionar uma verificação pra caso a chave já existisse. Mas com ele eu posso colocar `contagem_mensal[municipio][(ano, mes)] += 1`. Eu tentei fazer com dicionário normal mas começou a dar erro, aí pesquisando e pedindo ajuda me falaram da possibilidade de usar isso. E descobri que essa lib collections tem versões "melhoradas" dos tipos padrões, pelo que eu entendi.

2023-03-29 22:05 UTC, alex-custodio commented on docs/site/criar_json_diarios.py
> +        for diario in diarios:
Certo, vou refletir sobre isso.

2023-04-06 12:25 UTC, danielfireman requested changes
Dois pontos importantes:
- Usar os ids dos municípios como nomes para os arquivos jsons
- Adicionar algo que indique que eles serão usados na página inicial. Por exemplo, `craibas-inicial.json`
- Renomear o arquivo python para `site_home_data.py`

2023-04-06 12:25 UTC, danielfireman commented on docs/site/criar_jsons_diario.py
> +for path in glob.glob("data/diarios/*-resumo-extracao.json"):
Esse script deve ficar em docs/site mesmo? Sinto que se você executar aqui, não vai rodar.

Pq não movê-lo para a raiz? Dessa forma, vai funcionar.

2023-04-06 13:03 UTC, alex-custodio commented on docs/site/criar_jsons_diario.py
> +for path in glob.glob("data/diarios/*-resumo-extracao.json"):
Funciona Professor, essa linha está buscando a partir da pasta raiz e está gerando os arquivos, tanto que consegui executar desse jeito

2023-04-06 17:14 UTC, danielfireman commented on docs/site/criar_jsons_diario.py
> +for path in glob.glob("data/diarios/*-resumo-extracao.json"):
A linha não está buscando a partir da raiz, @alex-custodio,  isso eu tenho certeza. Talvez funcionou porque você executou a partir da raiz?

2023-04-07 01:09 UTC, alex-custodio commented on docs/site/criar_jsons_diario.py
> +for path in glob.glob("data/diarios/*-resumo-extracao.json"):
Sim, acredito que seja por causa da execução a partir do raiz mesmo. O senhor não acha interessante manter esse arquivo dentro da pasta site mesmo pra separar este script dos outros que não estão relacionados ao site?

2023-04-08 18:06 UTC, danielfireman requested changes
@alex-custodio os dados ainda contém informações sobre os dias, as quais aumentam o tamanho do arquivo a ser carregado e são irrelevantes no contexto da página inicial (ao menos até agora). Você deve agregar por ano e os arquivos da página inicial devem conter apenas informações agregadas.

2023-04-08 18:07 UTC, danielfireman commented on docs/site/criar_json_diarios.py
> +        for diario in diarios:
Note que, mais uma vez, você não seguiu o que combinamos aqui e nem explicou por que não seguiu.

2023-04-10 12:32 UTC, alex-custodio commented
@danielfireman Mas o senhor não acha que vai ser mais trabalho retirar agora e refazer depois? Porque em algum momento teremos que acessar isso e foi por isso que eu tinha feito: pra entregar tudo que foi pedido e mais um pouco.

2023-04-10 12:37 UTC, danielfireman commented
> @danielfireman Mas o senhor não acha que vai ser mais trabalho retirar agora e refazer depois? Porque em algum momento teremos que acessar isso e foi por isso que eu tinha feito: pra entregar tudo que foi pedido e mais um pouco.

O que acho que não está claro é que as informações a mais que você está tentando colocar estarão em *arquivos diferentes*. Colocar tudo num mesmo arquivo deixa o carregamento da página mais lento. Venho tentando te explicar isso desde que encontramos no meet, mas infelizmente não obtive sucesso. 

Somado a isso, muito provavelmente não serão todos os dias que iremos expor, mas somente os que contem nomeações e exonerações. Precisamos ir aprendendo passo a passo e vendo o que queremos mostrar. Colocar tudo agora não segue esse princípio.

Por fim, não acho que será muito mais trabalho criar outro script ou melhorar rar esse script para criar outros arquivos. O importante é que você está aprendendo.

2023-04-10 14:39 UTC, alex-custodio commented
Agora vou mandar um commit com as informações de ano, e dos meses pois são agregados necessários pra o cálculo de média de diários por exemplo. E eu consegui refatorar (novo termo que eu aprendi estudando KKKKKKK) o código e o simplificar.

2023-04-10 17:14 UTC, danielfireman approved these changes

2023-04-10 17:14 UTC, merged