Primeiros Passos: Extraindo CPF
danielfireman/ifal-qd pull request #99
Opened 2023-01-26 03:07 UTC by alex-custodio

2023-01-26 18:11 UTC, danielfireman requested changes

2023-01-26 18:11 UTC, danielfireman commented on post_proc.py
> +    # Quebra de linha ou espaço em branco (\s) e (\s\s), município Maragogi, 02/10/2018, ato B124090D; município INHAPI, 15/01/2021, ato 0E5005F9
Poderia colocar exemplos, por favor?

2023-01-26 18:11 UTC, danielfireman commented on post_proc.py
> +        self.cpf_nomeacoes = self._extrai_cpf()
Não deve ser chamado aqui. Deve ser extraído só os CPFs dos atos que há nomeações.

2023-01-26 18:11 UTC, danielfireman commented on post_proc.py
> +        #tratar exceção
Poderia documentar mais aqui? Dar exemplos?

2023-01-26 18:11 UTC, danielfireman commented on post_proc_test.py
> +                        if (ato_esperado.nomeacoes > 0):
Por isso que os testes passaram. Pois você só confere os CPFs quando o número de nomeações é maior que zero. Você deve conferir de todos. Quando não for nomeação é para retornar `cpf_nomeacao` nil ou vazio.

2023-01-26 19:10 UTC, alex-custodio commented on post_proc.py
> +        self.cpf_nomeacoes = self._extrai_cpf()
Então o método de extrair cpf deve ser chamado no `post_proc_test` ou dentro do método de extrai nomeações? Não entendi bem o que o senhor quis dizer aqui.

2023-01-26 19:58 UTC, danielfireman commented on post_proc.py
> +        self.cpf_nomeacoes = self._extrai_cpf()
Você só deve pagar o preço computacional de extrair CPFs de atos que você tem certeza que são nomeações.

2023-01-30 22:52 UTC, danielfireman approved these changes

2023-01-30 22:52 UTC, merged